title: Site
tabs:
  tabpages:
    label: Pages
    icon: page
    preset: pages
  tabconfig:
    label: Config
    icon: cog
    fields:
      seoTitle:
        label: SEO Title
        type: text
        width: 1/3
      seoDescription:
        label: SEO Description
        type: text
        width: 1/3
      seoImage:
        label: SEO image
        type: files
        width: 1/3
      skpmail:
        label: Contact mail
        type: email
        width: 1/2
      evelinamail:
        label: Evelina mail
        type: email
        width: 1/2
      socialtwitterURL:
        label: Twitter account
        type: url
        width: 1/2
      seoTags:
        label: seo Tags
        type: tags
      yearlyreports:
        label: Yearly Reports
        type: files
        width: 1/2
        multiple: true
        template: default

unlisted: true
